<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Section>
 */
class SectionFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $medicalSectionsArabic = [
            'القلب',
            'الأعصاب',
            'العظام',
            'الأطفال',
            'الأشعة',
            'الجلدية',
            'الأورام',
            'النساء والتوليد',
            'المسالك البولية',
            'الطب النفسي',
            'الجهاز الهضمي',
            'الغدد الصماء',
            'أمراض الدم',
            'الرئة',
            'الكلى',
            'العيون',
            'الأنف والأذن والحنجرة',
            'الروماتيزم',
            'الجراحة العامة',
            'جراحة التجميل',
            'جراحة الأوعية الدموية',
            'التخدير',
            'العناية المركزة',
            'الشيخوخة',
            'الطوارئ',
            'الطب العام',
            'الطب الرياضي',
            'المناعة',
            'الأمراض المعدية',
            'علم الأمراض',
            'الحساسية',
            'التأهيل',
            'إدارة الألم',
            'الصحة المهنية',
            'طب النوم',
            'الرعاية التلطيفية',
            'علم الوراثة',
            'طب الذكورة',
            'علم السموم',
            'الطب الوقائي',
            'الطب الشرعي',
            'الصيدلة الإكلينيكية',
            'التعليم الطبي',
            'البحث العلمي',
            'الطب النووي',
            'معلوماتية الصحة',
            'علم الأوبئة',
            'الإحصاء الحيوي',
            'طب الأوردة'
        ];
        $medicalSections = [
            'Cardiology',
            'Neurology',
            'Orthopedics',
            'Pediatrics',
            'Radiology',
            'Dermatology',
            'Oncology',
            'Gynecology',
            'Urology',
            'Psychiatry',
            'Gastroenterology',
            'Endocrinology',
            'Hematology',
            'Pulmonology',
            'Nephrology',
            'Ophthalmology',
            'ENT',
            'Rheumatology',
            'General Surgery',
            'Plastic Surgery',
            'Vascular Surgery',
            'Anesthesiology',
            'Critical Care',
            'Geriatrics',
            'Emergency Medicine',
            'Family Medicine',
            'Sports Medicine',
            'Immunology',
            'Infectious Disease',
            'Pathology',
            'Allergy',
            'Rehabilitation',
            'Pain Management',
            'Occupational Health',
            'Sleep Medicine',
            'Palliative Care',
            'Genetics',
            'Andrology',
            'Toxicology',
            'Preventive Medicine',
            'Forensic Medicine',
            'Clinical Pharmacology',
            'Medical Education',
            'Research',
            'Nuclear Medicine',
            'Health Informatics',
            'Epidemiology',
            'Biostatistics',
            'Phlebology'
        ];
        static $index = 0;
        return [
            'name' => $medicalSections[$index++],
        ];
    }
}
//



// INSERT INTO `section_translations` (`id`, `locale`, `section_id`, `name`) VALUES
// -- English Translations
// (1, 'en', 1, 'Cardiology'),
// (2, 'en', 2, 'Neurology'),
// (3, 'en', 3, 'Orthopedics'),
// (4, 'en', 4, 'Pediatrics'),
// (5, 'en', 5, 'Radiology'),
// (6, 'en', 6, 'Dermatology'),
// (7, 'en', 7, 'Oncology'),
// (8, 'en', 8, 'Gynecology'),
// (9, 'en', 9, 'Urology'),
// (10, 'en', 10, 'Psychiatry'),
// (11, 'en', 11, 'Gastroenterology'),
// (12, 'en', 12, 'Endocrinology'),
// (13, 'en', 13, 'Hematology'),
// (14, 'en', 14, 'Pulmonology'),
// (15, 'en', 15, 'Nephrology'),
// (16, 'en', 16, 'Ophthalmology'),
// (17, 'en', 17, 'ENT'),
// (18, 'en', 18, 'Rheumatology'),
// (19, 'en', 19, 'General Surgery'),
// (20, 'en', 20, 'Plastic Surgery'),
// (21, 'en', 21, 'Vascular Surgery'),
// (22, 'en', 22, 'Anesthesiology'),
// (23, 'en', 23, 'Critical Care'),
// (24, 'en', 24, 'Geriatrics'),
// (25, 'en', 25, 'Emergency Medicine'),
// (26, 'en', 26, 'Family Medicine'),
// (27, 'en', 27, 'Sports Medicine'),
// (28, 'en', 28, 'Immunology'),
// (29, 'en', 29, 'Infectious Disease'),
// (30, 'en', 30, 'Pathology'),
// (31, 'en', 31, 'Allergy'),
// (32, 'en', 32, 'Rehabilitation'),
// (33, 'en', 33, 'Pain Management'),
// (34, 'en', 34, 'Occupational Health'),
// (35, 'en', 35, 'Sleep Medicine'),
// (36, 'en', 36, 'Palliative Care'),
// (37, 'en', 37, 'Genetics'),
// (38, 'en', 38, 'Andrology'),
// (39, 'en', 39, 'Toxicology'),
// (40, 'en', 40, 'Preventive Medicine'),
// (41, 'en', 41, 'Forensic Medicine'),
// (42, 'en', 42, 'Clinical Pharmacology'),
// (43, 'en', 43, 'Medical Education'),
// (44, 'en', 44, 'Research'),
// (45, 'en', 45, 'Nuclear Medicine'),
// (46, 'en', 46, 'Health Informatics'),
// (47, 'en', 47, 'Epidemiology'),
// (48, 'en', 48, 'Biostatistics'),
// (49, 'en', 49, 'Phlebology'),

// -- Arabic Translations
// (50, 'ar', 1, 'القلب'),
// (51, 'ar', 2, 'الأعصاب'),
// (52, 'ar', 3, 'العظام'),
// (53, 'ar', 4, 'الأطفال'),
// (54, 'ar', 5, 'الأشعة'),
// (55, 'ar', 6, 'الجلدية'),
// (56, 'ar', 7, 'الأورام'),
// (57, 'ar', 8, 'النساء والتوليد'),
// (58, 'ar', 9, 'المسالك البولية'),
// (59, 'ar', 10, 'الطب النفسي'),
// (60, 'ar', 11, 'الجهاز الهضمي'),
// (61, 'ar', 12, 'الغدد الصماء'),
// (62, 'ar', 13, 'أمراض الدم'),
// (63, 'ar', 14, 'الرئة'),
// (64, 'ar', 15, 'الكلى'),
// (65, 'ar', 16, 'العيون'),
// (66, 'ar', 17, 'الأنف والأذن والحنجرة'),
// (67, 'ar', 18, 'الروماتيزم'),
// (68, 'ar', 19, 'الجراحة العامة'),
// (69, 'ar', 20, 'جراحة التجميل'),
// (70, 'ar', 21, 'جراحة الأوعية الدموية'),
// (71, 'ar', 22, 'التخدير'),
// (72, 'ar', 23, 'العناية المركزة'),
// (73, 'ar', 24, 'الشيخوخة'),
// (74, 'ar', 25, 'الطوارئ'),
// (75, 'ar', 26, 'الطب العام'),
// (76, 'ar', 27, 'الطب الرياضي'),
// (77, 'ar', 28, 'المناعة'),
// (78, 'ar', 29, 'الأمراض المعدية'),
// (79, 'ar', 30, 'علم الأمراض'),
// (80, 'ar', 31, 'الحساسية'),
// (81, 'ar', 32, 'التأهيل'),
// (82, 'ar', 33, 'إدارة الألم'),
// (83, 'ar', 34, 'الصحة المهنية'),
// (84, 'ar', 35, 'طب النوم'),
// (85, 'ar', 36, 'الرعاية التلطيفية'),
// (86, 'ar', 37, 'علم الوراثة'),
// (87, 'ar', 38, 'طب الذكورة'),
// (88, 'ar', 39, 'علم السموم'),
// (89, 'ar', 40, 'الطب الوقائي'),
// (90, 'ar', 41, 'الطب الشرعي'),
// (91, 'ar', 42, 'الصيدلة الإكلينيكية'),
// (92, 'ar', 43, 'التعليم الطبي'),
// (93, 'ar', 44, 'البحث العلمي'),
// (94, 'ar', 45, 'الطب النووي'),
// (95, 'ar', 46, 'معلوماتية الصحة'),
// (96, 'ar', 47, 'علم الأوبئة'),
// (97, 'ar', 48, 'الإحصاء الحيوي'),
// (98, 'ar', 49, 'طب الأوردة');
